# All services are defined under the top-level 'services' key
services:
  # -------------------
  # The React Frontend (Static Site)
  # -------------------
  - name: pitchine-client
    type: web
    runtime: static # This combination defines a static site on Render
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: build # Use 'staticPublishPath' for static sites
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: pitchine-api
          property: url
      - key: REACT_APP_WEBSOCKET_URL
        fromService:
          type: web
          name: pitchine-api
          property: url
          modify: "sed 's/^http/ws/'"

  # ------------------
  # The Python Backend (Web Service)
  # ------------------
  - type: web
    name: pitchine-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SESSION_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web # The frontend is also a type of web service
          name: pitchine-client
          property: url
    secretFiles:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        name: gcp_creds.json
        mountPath: /etc/secrets/gcp_creds.json
      - key: FIREBASE_SERVICE_ACCOUNT
        name: firebase_creds.json
        mountPath: /etc/secrets/firebase_creds.json
