# All services are defined under this single top-level 'services' key.
services:
  # -------------------
  # The React Frontend (Static Site)
  # -------------------
  - type: static_site  # This is the correct type name.
    name: pitchine-client
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    publishDir: build # This key is valid ONLY when type is 'static_site'.
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web # This references the type of the 'pitchine-api' service below.
          name: pitchine-api
          property: url
      - key: REACT_APP_WEBSOCKET_URL
        fromService:
          type: web
          name: pitchine-api
          property: url
          modify: "sed 's/^http/ws/'"

  # ------------------
  # The Python Backend (Web Service)
  # ------------------
  - type: web
    name: pitchine-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FRONTEND_URL
        fromService:
          type: static_site # This correctly references the type of the 'pitchine-client' service above.
          name: pitchine-client
          property: url
      # IMPORTANT: Add your secret keys and files in the Render Dashboard,
      # not directly in this file. You will set GOOGLE_CLIENT_ID, GEMINI_API_KEY, etc.
      # in the Environment tab of your 'pitchine-api' service after the blueprint is created.
