services:
  # ------------------
  # The Python Backend
  # ------------------
  - type: web
    name: pitchine-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SESSION_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: static # Corrected: This must match the type of the frontend service
          name: pitchine-client
          property: url
    secretFiles:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        name: gcp_creds.json
        mountPath: /etc/secrets/gcp_creds.json
      - key: FIREBASE_SERVICE_ACCOUNT
        name: firebase_creds.json
        mountPath: /etc/secrets/firebase_creds.json

  # -------------------
  # The React Frontend
  # -------------------
  - type: static # CORRECTED: This is the required type for a static site.
    name: pitchine-client
    # Since your React app is in the 'frontend' subfolder,
    # we need to tell Render where to look for it.
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    publishDir: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: pitchine-api
          property: url
      - key: REACT_APP_WEBSOCKET_URL
        fromService:
          type: web
          name: pitchine-api
          # Transform https:// to wss:// for WebSocket connection
          property: url
          modify: "sed 's/^http/ws/'"
