# All services are defined under this single top-level 'services' key.
services:
  # -------------------
  # The React Frontend (Static Site)
  # -------------------
  - type: web  # This IS the correct type for a static site.
    name: pitchine-client
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    publishDir: build # 'publishDir' is CORRECT for 'type: static_site'.
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web # The service type we are referencing (the API below)
          name: pitchine-api
          property: url
      - key: REACT_APP_WEBSOCKET_URL
        fromService:
          type: web
          name: pitchine-api
          property: url
          modify: "sed 's/^http/ws/'"

  # ------------------
  # The Python Backend (Web Service)
  # ------------------
  - type: web
    name: pitchine-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # These values MUST be set in the Render Dashboard Environment.
      # The secret files themselves are also set in the dashboard.
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcp_creds.json
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: /etc/secrets/firebase_creds.json
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SESSION_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: static_site # Reference the service by its correct type.
          name: pitchine-client
          property: url
